### ISSUE TITLE
OAuth not working

### ISSUE THREAD

**Issue by brwa-ata** [JuanDMeGon/RESTful-API-with-Laravel-Definitive-Guide#2]
I have an issue with oauth, it doesn't working i tried `php artisan passport:client --personal` and then ran `npm run dev` but it still not working and it doesn't give me any error just show the empty view this is my code please check my code , **BUT** my _passport version is 4.0_ and _yours are  2.0_

`app.js`
require('./bootstrap');

window.Vue = require('vue');

Vue.component(
    'passport-clients',
    require('./components/passport/Clients.vue')
);

Vue.component(
    'passport-authorized-clients',
    require('./components/passport/AuthorizedClients.vue')
);

Vue.component(
    'passport-personal-access-tokens',
    require('./components/passport/PersonalAccessTokens.vue')
);

const app = new Vue({
    el: '#app'
});

`routes/web`
Route::get('/home/authorized-clients', 'HomeController@getAuthorizedClients')->name('authorized-clients');
Route::get('/home/my-clients', 'HomeController@getClients')->name('personal-clients');
Route::get('/home/my-tokens', 'HomeController@getTokens')->name('personal-tokens');

`HomeController`

    public function getTokens()
    {
        return view('home.personal-tokens');
    }

    public function getAuthorizedClients()
    {
        return view('home.authorized-clients');
    }

    public function getClients()
    {
        return view('home.personal-clients');
    }

`view/home/personal-tokens`

@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                       <passport-personal-access-tokens></passport-personal-access-tokens>
            </div>
        </div>
    </div>

@endsection

**Comment by JuanDMeGon** [comment]
Hello, sorry for the possible confusion.
Please share your doubts on the course platform, there I will be able to reply for all students.

When I said share your code on Github, was talking about sharing your whole project on a repository of you, on GitHub, in that way I will be able to obtain your complete project and try to reproduce the issue and maybe solve it.

Best wishes.

**Comment by brwa-ata** [comment]
Oh sorry, I already share it on my github this is the link  https://github.com/brwa-ata/API
sorry for this annoy but really really I want it
