### ISSUE TITLE
Issue with update method

### ISSUE THREAD

**Issue by brijeshdave** [JuanDMeGon/RESTful-API-with-Laravel-Definitive-Guide#3]
In all controller;s update method in this code where are we checking the validation for rules we created.

i.e. if in this code in UserController's update method if i have a username field that i put a rule to be required and must be a string.

now i want in update method that it should follow that rules before validating i mean should throw a validation error if someone passes empty string or like numeric value.

for now i can't see that we are checking the rules in update method. 

i tried to do it with $this->validate($request, $rules); but it fails showing unknown column error and the column it is looking for is the id that we are trying to update.

what is the right way to do that?

**Comment by JuanDMeGon** [comment]
Hello,

Sure, calling to $request->validate(...) may work properly for your routes. Just remember that ID is an auto-increment field so we do not need to update this value, in fact, you should never update the ID of any record, as in this case, for example, you are using that ID to determine which entity to update.

Now, cannot be sure why this might be failing in your case as I don't know what rules are you using and what request fields are you sending.

**Comment by brijeshdave** [comment]
hey Juan thx for the reply it was really quick.

firstly i'm sorry for the issue about unknown column was clearly my stupid mistake defining rules for unique validation. sorry for that i am new to all this stuff.

and about the validation in update method when i tried with $this->validate($request, $rules); it was giving all the errors even if i wanted to update only single field.

so i came up with the following solution to that it will check only for the field that i am trying to update.

$rules = [
        	// ..... My rules
        ];

        $rules = array_intersect_key($rules,$request->all());
            
        $this->validate($request, $rules);
// my code after validation

in this way it is only validates the filed that i pass to update in $request.

and i got what i want. Happy now.

Thank you for the help.
